services:
    app:
        container_name: the-joy-box
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - ${DOCKER_PORT:-3000}:3000
        restart: unless-stopped
