import type { Metadata } from "next"
import { Phudu } from "next/font/google"
import "./globals.css"

const PhuduFont = Phudu({
    variable: "--font-phudu",
    subsets: ["latin"],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${PhuduFont.variable} antialiased`}>
                {children}
            </body>
        </html>
    )
}
